### ISSUE TITLE
`border_ringbuf_max_entries` only displays entries for 1101, nothing about `ffaa:0:1107`

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/2SMS#1]
https://grafana.scionlab.org has a testing board, where we added `border_ringbuf_max_entries`, but we see metrics only for `ffaa:0:1101`, and nothing for our AP in `ffaa:0:1107`.
We should see `border_ringbuf_max_entries` also for our BR in our AP

**Comment by baehless** [comment]
```border_ringbuf_max_entries{AS="ffaa:0:1101",ISD="17",desc="free",elem="br17-ffaa_0_1101-1",instance="193.247.172.130:9199",job="17-ffaa:0:1101 193.247.172.130 br",ringId="freePkts",service="br"}``` is the only query regarding ```border_ringbuf_max_entries``` and it does indeed select only ```ffaa:0:1101``` so the behaviour is correct. If you wish to see also ```ffaa:0:1107``` you can either modify the existing query or add a new one.

**Comment by juagargi** [comment]
Yup. I see `ffaa:0:1107`, but there are no values. I've updated the dashboard with a graph showing `border_ringbuf_used_entries{ringId='freePkts'}` , there we see two metrics, for `ffaa:0:1101` and for `ffaa:0:1107`, but the one for `ffaa:0:1107` is pretty much empty. 
If you switch the period to e.g. "last 2 days" there are no values for `ffaa:0:1107`. Please take a look at the board.

**Comment by baehless** [comment]
That's because the services are not yet reachable, if you check the ```up``` metric you'll see that 1107 still is not exposing data correctly. And the same problem will occur on any other machine as long as the services aren't restarted with the new ```-prom``` argument.

**Comment by juagargi** [comment]
Now it does work.
