### ISSUE TITLE
Receive alerts when target is not there

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/2SMS#25]
E.g. if `/br` has been moved to `/br-1` there is no `/br` anymore and we should receive an alert --because the scraper could have not been able to get metrics for that target--. 
Check with an AP other than `1-17`.

**Comment by baehless** [comment]
Not clear what happened since it occurred during testing of new features and the system's state wasn't clean. Anyway even in a correct state we wouldn't get alerts for unreachable local targets. See #37
