### ISSUE TITLE
Fix seg fault

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/2SMS#27]
In the manager, maybe other places as well, it seems to happen when the certificate has changed. Avoid crashing and just give out a meaningful message.
Stack: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1074797]

goroutine 1 [running]:
github.com/scionproto/scion/go/lib/crypto/cert.(*Chain).Verify(0x0, 0x11, 0xffaa0001000a, 0xc420261880, 0xc4203665a0, 0x0)
	/home/juan/go/src/github.com/scionproto/scion/go/lib/crypto/cert/chain.go:125 +0x37
github.com/netsec-ethz/2SMS/common.Bootstrap(0x16e023a, 0x9, 0x16f31a2, 0x11, 0x16e0011, 0xffaa00010062, 0xc4200d42d0, 0x0)
	/home/juan/go/src/github.com/netsec-ethz/2SMS/common/pki.go:37 +0x1bf
main.init.0()
	/home/juan/go/src/github.com/netsec-ethz/2SMS/manager/manager.go:137 +0x62d
```

**Comment by baehless** [comment]
With #50 we removed the called to `github.com/scionproto/scion/go/lib/crypto/cert.(*Chain).Verify` (`crypto` has meanwhile been renamed to `scrypto`) that caused the Manager to panic, so this segmentation fault can't happen in the current version. However this problem must be taken into account when solving #38.
Thus closing.
