### ISSUE TITLE
endpoint stuck in PUT

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/2SMS#63]
The `update_gen.py` script contacted the endpoint with the `PUT` to update the border router targets, and never came back. This happened in AS 1-17.
Data: AS 1-17, `syslog.2.gz`.
8th 17:47:47 `updateGen.sh` PID 7386 started
8th 19:05:42 `updateGen.sh` PID 7386 finished

After this, `systemd` will execute another instance of `updateGen.sh` because the timer expired. That's the reason we see in the logs a new update happening right after the other one.

**Comment by baehless** [comment]
The problem is caused by the Prometheus server in the Scraper: the time required for reloading was around 2-3 minutes and being a reload per target still required and the operations in the update synchronous the total time for updating all BRs increased by a lot.

**Comment by baehless** [comment]
Updating to the newest Prometheus version solved the problem, but the APIs should be still improved (#34, #58) to avoid the problem at the root.
